"""
summarize.py — Send extracted paper text to AWS Bedrock (Claude Sonnet)
for summarization and code/data detection.

Usage:
    python summarize.py

Prerequisites:
    - ~/.aws/credentials configured with Bedrock access
    - Bedrock model access enabled for Claude Sonnet in us-west-2
    - tober_2025_extracted.txt exists (run extract_text.py first)

Output:
    - Prints summary and code/data assessment to console
    - Writes results to tober_2025_summary.md
    - Reports token usage and estimated cost
"""

import boto3
import json
from pathlib import Path

# --- Configuration ---
REGION = "us-west-2"
MODEL_ID = "us.anthropic.claude-sonnet-4-6"
INPUT_PATH = Path(__file__).parent / "tober_2025_extracted.txt"
OUTPUT_PATH = Path(__file__).parent / "tober_2025_summary.md"

# Bedrock pricing (Claude Sonnet, us-west-2, as of mid-2025)
COST_PER_1K_INPUT_TOKENS = 0.003
COST_PER_1K_OUTPUT_TOKENS = 0.015


def build_prompt(paper_text: str) -> str:
    """Construct the prompt for summarization + code/data detection."""
    return f"""You are a scientific research assistant. I will provide the full text
of an academic paper. Please do the following:

1. **Summary**: Provide a structured summary of the paper including:
   - Title and authors
   - Research question / objective
   - Methods used
   - Key findings
   - Significance / implications

2. **Code and Data Availability**: Determine whether the paper references:
   - A code repository (GitHub, GitLab, Bitbucket, Zenodo, etc.)
   - A data repository or dataset with a URL or DOI
   - If found, provide the exact URLs/DOIs
   - If not found, state that clearly

3. **Reproducibility Assessment**: Based on what you find, briefly assess how
   reproducible this work would be for another researcher.

Here is the paper text:

---
{paper_text}
---

Please respond in well-structured markdown."""


def call_bedrock(prompt: str) -> dict:
    """Invoke Claude Sonnet via Bedrock and return the response with metadata."""
    client = boto3.client("bedrock-runtime", region_name=REGION)

    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 4096,
        "messages": [
            {"role": "user", "content": prompt}
        ]
    })

    response = client.invoke_model(
        modelId=MODEL_ID,
        contentType="application/json",
        accept="application/json",
        body=body
    )

    result = json.loads(response["body"].read())

    return {
        "text": result["content"][0]["text"],
        "input_tokens": result["usage"]["input_tokens"],
        "output_tokens": result["usage"]["output_tokens"],
    }


def compute_cost(input_tokens: int, output_tokens: int) -> float:
    """Estimate cost in USD."""
    input_cost = (input_tokens / 1000) * COST_PER_1K_INPUT_TOKENS
    output_cost = (output_tokens / 1000) * COST_PER_1K_OUTPUT_TOKENS
    return input_cost + output_cost


if __name__ == "__main__":
    # Load extracted text
    if not INPUT_PATH.exists():
        print(f"ERROR: {INPUT_PATH} not found. Run extract_text.py first.")
        raise SystemExit(1)

    paper_text = INPUT_PATH.read_text(encoding="utf-8")
    print(f"Loaded paper text: {len(paper_text):,} characters")

    # Build prompt and call Bedrock
    prompt = build_prompt(paper_text)
    print(f"Calling Bedrock ({MODEL_ID}) in {REGION}...")
    print("(This may take 15-30 seconds)")

    result = call_bedrock(prompt)

    # Display results
    print("\n" + "=" * 60)
    print("SUMMARY AND ANALYSIS")
    print("=" * 60)
    print(result["text"])

    # Token usage and cost
    input_tokens = result["input_tokens"]
    output_tokens = result["output_tokens"]
    cost = compute_cost(input_tokens, output_tokens)

    print("\n" + "=" * 60)
    print("TOKEN USAGE AND COST")
    print("=" * 60)
    print(f"Input tokens:  {input_tokens:,}")
    print(f"Output tokens: {output_tokens:,}")
    print(f"Estimated cost: ${cost:.2f}")

    # Write output
    output_content = f"""# Summary: Tober et al. — Alaskan Glacier Depths

> Generated by Claude Sonnet via AWS Bedrock
> Model: {MODEL_ID}
> Input tokens: {input_tokens:,} | Output tokens: {output_tokens:,}
> Estimated cost: ${cost:.2f}

---

{result["text"]}
"""
    OUTPUT_PATH.write_text(output_content, encoding="utf-8")
    print(f"\nResults written to: {OUTPUT_PATH.name}")
